FROM niiiix/debian:mini-latest
LABEL MAINTAINER="Sadegh Khademi" EMAIL="khademi.sadegh@gmail.com"

COPY ./app/* /usr/local/

RUN chmod +x /usr/local/bin/helm /usr/local/bin/kubectl /usr/local/bin/yq

CMD bash
